backend:
  name: git-gateway
  branch: main
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: blog
    label: Blog
    folder: public/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", default: "Micheal Ohagwam" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, field: { label: "Tag", name: "tag", widget: "string" } }
      - { label: "Category", name: "category", widget: "select", options: ["Education", "News", "Tutorials", "Analysis", "Community"], default: "Education" }
      - { label: "Featured Post", name: "featured", widget: "boolean", default: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }